import { Colors } from "@/src/constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        width: '100%',
        backgroundColor: Colors.light.background,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#719EC0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        overflow: 'hidden',
        marginVertical: 10,
        fontFamily: 'Poppins_500Medium',
    },
    header: {
        backgroundColor: '#154FBF',
        borderTopLeftRadius: 5,
        borderTopRightRadius: 5,
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingRight: 10,
        paddingBottom: 10,
        flexDirection: 'row'
    },
    contentContainer: {
        backgroundColor: '#154FBF',
        paddingBottom: 15,
    },
    specialty: {
        fontFamily: 'Poppins_600SemiBold',
        fontSize: 16,
        color: '#FFFFFF',
        marginTop: 10,
        marginLeft: 15,
    },
    doctorName: {
        fontFamily: 'Poppins_600SemiBold',
        fontSize: 12,
        color: '#FFFFFF',
        marginLeft: 15,
    },
    patientInfoContainer: {
        flexDirection: 'row',
        marginTop: 10,
        marginLeft: 15,
        alignItems: 'center',
    },
    avatarContainer: {
        marginRight: 10,
    },
    avatarText: {
        fontSize: 20,
    },
    patientDetails: {
        flex: 1,
    },
    patientName: {
        fontFamily: 'Poppins_500Medium',
        fontSize: 14,
        color: '#000000',
    },
    patientAge: {
        fontFamily: 'Poppins_500Medium',
        fontSize: 14,
        color: '#000000',
    },
    medicalRecordContainer: {
        marginTop: 10,
        marginLeft: 15,
        marginRight: 15,
    },
    medicalRecordText: {
        fontFamily: 'Poppins_400Regular',
        fontSize: 12,
        color: '#000000',
        lineHeight: 18,
    },
    medicalRecordRow: {
        flexDirection: 'row',
    },
    medicalRecordLabel: {
        fontFamily: 'Poppins_400Regular',
        fontSize: 12,
        color: '#154FBF',
        lineHeight: 18,
    },
    iconsContainer: {
        flexDirection: 'row',
        marginTop: 10,
        marginLeft: 15,
    },
    iconItem: {
        marginRight: 10,
    },
    selectorContainer: {
        marginTop: 15,
        marginLeft: 15,
        marginRight: 15,
        marginBottom: 15,
    },
    selectorLabel: {
        fontFamily: 'Poppins_500Medium',
        fontSize: 14,
        color: '#154FBF',
        marginBottom: 8,
    },
    loadingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 12,
    },
    loadingText: {
        fontFamily: 'Poppins_400Regular',
        fontSize: 14,
        color: '#719EC0',
    },
    errorContainer: {
        borderWidth: 1,
        borderColor: '#FF3B3050',
        borderRadius: 6,
        padding: 12,
        backgroundColor: '#FF3B3010',
        gap: 8,
    },
    errorText: {
        fontFamily: 'Poppins_500Medium',
        color: '#FF3B30',
        fontSize: 14,
    },
    retryButton: {
        alignSelf: 'flex-start',
    },
    retryText: {
        fontFamily: 'Poppins_500Medium',
        color: '#154FBF',
        fontSize: 14,
        textDecorationLine: 'underline',
    },
    emptyText: {
        fontFamily: 'Poppins_400Regular',
        color: '#719EC0',
        fontSize: 14,
        paddingVertical: 12,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    }, 
    loadingPatientContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#F5F9FF',
        borderRadius: 8,
        marginHorizontal: 15,
        marginVertical: 10,
    },
    loadingPatientText: {
        fontFamily: 'Poppins_400Regular',
        fontSize: 14,
        color: '#719EC0',
        marginLeft: 12,
    },
    errorPatientContainer: {
        backgroundColor: '#FFF5F5',
        borderColor: '#FFE0E0',
        borderWidth: 1,
        borderRadius: 8,
        padding: 16,
        marginHorizontal: 15,
        marginVertical: 10,
        alignItems: 'center',
    },
    errorIcon: {
        width: 24,
        height: 24,
        marginBottom: 8,
    },
    errorPatientText: {
        fontFamily: 'Poppins_500Medium',
        color: '#FF3B30',
        fontSize: 14,
        textAlign: 'center',
    },
    emptyPatientContainer: {
        backgroundColor: '#F8F9FB',
        borderRadius: 8,
        padding: 24,
        marginHorizontal: 15,
        marginVertical: 10,
        alignItems: 'center',
    },
    emptyIcon: {
        width: 32,
        height: 32,
        marginBottom: 12,
        tintColor: '#A3B8D1',
    },
    emptyPatientText: {
        fontFamily: 'Poppins_400Regular',
        fontSize: 14,
        color: '#719EC0',
        textAlign: 'center',
    },
});